import React, {Suspense, useEffect, useMemo, useRef, useState, Component} from 'react';
import {Canvas, useFrame, useThree} from '@react-three/fiber';
import {OrbitControls, useGLTF, useAnimations, Html, useProgress} from '@react-three/drei';
import * as THREE from 'three';

class SceneBoundary extends Component {state={failed:false};static getDerivedStateFromError(){return {failed:true}}componentDidCatch(){this.props.onFallback?.()}render(){return this.state.failed?null:this.props.children}}
function Loading(){const {progress}=useProgress();return <Html center><span className="scene-loading">{Math.round(progress)}% · Loading workspace</span></Html>}
function Model({kind,paused,onReady}){const {scene,animations}=useGLTF(`./models/${kind}-workspace.glb`);const {actions}=useAnimations(animations,scene);useEffect(()=>{onReady?.()},[scene,onReady]);useEffect(()=>{Object.values(actions).forEach(a=>{a.play();a.paused=paused});return()=>Object.values(actions).forEach(a=>a.stop())},[actions,paused]);return <primitive object={scene}/>}
function Controls({reset,zoomRequest}){
 const orbit=useRef();const {camera,size}=useThree();
 const fitted=Math.min(size.width/7.4,size.height/6.7);
 useEffect(()=>{camera.position.set(6.5,6.5,8.5);camera.zoom=fitted;camera.updateProjectionMatrix();orbit.current?.target.set(0,1.65,.2);orbit.current?.update()},[reset,camera,fitted]);
 useEffect(()=>{if(!zoomRequest?.step)return;camera.zoom=THREE.MathUtils.clamp(camera.zoom*(zoomRequest.step>0?1.18:1/1.18),fitted*.75,fitted*1.9);camera.updateProjectionMatrix();orbit.current?.update()},[zoomRequest,camera,fitted]);
 return <OrbitControls ref={orbit} target={[0,1.65,.2]} enableZoom enablePan={false} minZoom={fitted*.75} maxZoom={fitted*1.9} zoomSpeed={.55} rotateSpeed={.65} minPolarAngle={.3} maxPolarAngle={1.48} enableDamping dampingFactor={.075}/>;
}
export default function Scene({kind,paused,reset,zoomRequest,onReady,onFallback}){const holder=useRef(),[active,setActive]=useState(true),[supported]=useState(()=>{try{const c=document.createElement('canvas');const gl=c.getContext('webgl2');if(gl){gl.getExtension('WEBGL_lose_context')?.loseContext();return true}return false}catch{return false}});useEffect(()=>{if(!holder.current)return;const ob=new IntersectionObserver(([e])=>setActive(e.isIntersecting));ob.observe(holder.current);const visibility=()=>setActive(!document.hidden);document.addEventListener('visibilitychange',visibility);return()=>{ob.disconnect();document.removeEventListener('visibilitychange',visibility)}},[]);if(!supported)return null;return <div ref={holder} className="scene-canvas" role="img" aria-label={kind==='hero'?'Interactive 3D developer workspace. Drag for 360° rotation; scroll or pinch to zoom.':'Animated character listening to music at a laptop. Drag for 360° rotation; scroll or pinch to zoom.'}><SceneBoundary onFallback={onFallback}><Canvas orthographic camera={{position:[6.5,6.5,8.5],zoom:65,near:.1,far:100}} dpr={[1,1.5]} frameloop={active?'always':'never'} gl={{alpha:true,antialias:true,powerPreference:'low-power'}} onCreated={({gl})=>{gl.setClearColor('#101217',0);gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.3;gl.domElement.addEventListener('webglcontextlost',()=>{gl.domElement.style.display='none';onFallback?.()})}}><ambientLight intensity={.8}/><hemisphereLight args={['#b9d2ff','#373132',2]}/><directionalLight position={[2,6,4]} intensity={3.1} color="#d9e7ff"/><directionalLight position={[-4,3,1]} intensity={2} color="#ffe0bc"/><directionalLight position={[2,4,-4]} intensity={3} color="#7da8ff"/><Suspense fallback={<Loading/>}><Model kind={kind} paused={paused||!active} onReady={onReady}/></Suspense><Controls reset={reset} zoomRequest={zoomRequest}/></Canvas></SceneBoundary></div>}
